### PR TITLE
Trabalho de IC 2.0

### PR DESCRIPTION
**Pull request by luan1221**
[lssa.zip](https://github.com/fernandocastor/if668_2018_1/files/1939273/lssa.zip)

### CODE REVIEW

**Comment by luan1221** [comment]
[lssa.pdf](https://github.com/fernandocastor/if668_2018_1/files/1995278/lssa.pdf)

**Comment by luan1221** [comment]
https://git.overleaf.com/16002617fkxrbqjmjyrq

**Comment by luan1221** [comment]
[lssa.pdf](https://github.com/fernandocastor/if668_2018_1/files/1995290/lssa.pdf)
https://git.overleaf.com/16002617fkxrbqjmjyrq

**Comment by luan1221** [comment]
[lssa.pdf](https://github.com/fernandocastor/if668_2018_1/files/1995293/lssa.pdf)

**Comment by godsavemenow** [comment]
All > Draven

**Pull request merged**
